name: CI

on:
  push:
    branches: [ master, nixify ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Setup Dhall
      uses: dhall-lang/setup-dhall@v4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        $(nix-build docker.nix) | docker load
        LOCAL_VERSION=$(dhall text < ./version.dhall)
        docker tag  ghcr.io/jcouyang/orgpress:latest ghcr.io/jcouyang/orgpress:$LOCAL_VERSION
        docker push ghcr.io/jcouyang/orgpress:latest
        docker push ghcr.io/jcouyang/orgpress:$LOCAL_VERSION
  test:
    runs-on: ubuntu-latest
    needs:
      - build-docker
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: public
    - name: Setup Dhall
      uses: dhall-lang/setup-dhall@v4
    - run: |
        rm -rf public/*
        rm -rf public/.org-timestamps
        LOCAL_VERSION=$(dhall text < ./version.dhall)
        docker run --rm -v $(pwd):/blog ghcr.io/jcouyang/orgpress:$LOCAL_VERSION
        cd public
        git add .
        git config user.email "oyanglulu@gmail.com"
        git config user.name "orgpress"
        git commit -m "orgpress publish"
        git push origin gh-pages
